Repository wortell/AZSentinel, pull requests merged in 2020-09, with the labels that each got.

#90 Feature - Adding support for all alert rule types
  AzSentinel/Classes/AlertRule.ps1
  AzSentinel/Classes/Fusion.ps1
  AzSentinel/Classes/MLBehaviorAnalytics.ps1
  AzSentinel/Classes/MicrosoftSecurityIncidentCreation.ps1
  AzSentinel/Classes/classes.psd1
  AzSentinel/Public/Get-AzSentinelAlertRule.ps1
  AzSentinel/Public/Import-AzSentinelAlertRule.ps1
  AzSentinel/Public/New-AzSentinelAlertRule.ps1
  AzSentinel/Public/New-AzSentinelAlertRuleAction.ps1
  AzSentinel/Public/Remove-AzSentinelAlertRuleAction.ps1
  AzSentinel/docs/Get-AzSentinelAlertRule.md
  AzSentinel/docs/New-AzSentinelAlertRule.md
  AzSentinel/docs/Rename-AzSentinelAlertRule.md
  AzSentinel/enums/Kind.ps1
  README.md
  docs/Get-AzSentinelAlertRule.md
  docs/New-AzSentinelAlertRule.md
  docs/Rename-AzSentinelAlertRule.md
  examples/AlertRules.json
Labels: enhancement

#94 New Functionality to get alert rule templates provided by Microsoft
  AzSentinel/Public/Get-AzSentinelAlertRuleTemplates.ps1
Labels: enhancement

#104 Updating example files
  examples/AlertRules.yaml
  examples/SuspectApplicationConsent.yaml
Labels: documentation

#102 Fix - Get-AzSentinelAlertRuleAction doesn't return playbookName
  AzSentinel/Public/Get-AzSentinelAlertRule.ps1
Labels: bug, enhancement

#106 Fix - get-azsentinelhuntingrule updated get and remove function
  AzSentinel/Public/Get-AzSentinelHuntingRule.ps1
  AzSentinel/Public/Remove-AzSentinelHuntingRule.ps1
Labels: bug, enhancement

#107 Filter rules by lastModified date
  AzSentinel/Public/Get-AzSentinelAlertRule.ps1
  AzSentinel/docs/Get-AzSentinelAlertRule.md
  docs/Get-AzSentinelAlertRule.md
Labels: enhancement
